name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        features: [ "async-std-native-tls", "async-std-rustls-tls", "tokio-native-tls", "tokio-rustls-tls" ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check
        run: cargo clippy --verbose --no-default-features --features=${{ matrix.features }}
      - name: Build
        run: cargo build --verbose --no-default-features --features=${{ matrix.features }}
      - name: Run tests
        run: cargo test --verbose --no-default-features --features=${{ matrix.features }}
